const API='/api';const grace=5,finalWindow=5;let state={user:null,students:[],timetable:[],attendance:[],movement:[],holidays:[],notifications:[],tempRequested:false,stream:null,regStream:null,descriptorsLoaded:false};
const $=id=>document.getElementById(id); const dateStr=()=>new Date().toISOString().slice(0,10); const timeStr=()=>new Date().toTimeString().slice(0,8);
async function api(resource,opts={}){let r=await fetch(`${API}?resource=${resource}${opts.query||''}`,{headers:{'Content-Type':'application/json'},...opts});let j=await r.json();if(!r.ok)throw Error(j.error||'API error');return j}
async function login(){const u=$('username').value.trim(),p=$('password').value;try{let j=await api('login',{method:'POST',body:JSON.stringify({username:u,password:p})});state.user=j;openApp();await load();}catch(e){$('loginMsg').textContent=e.message;localLogin(u,p)}}
function localLogin(u,p){if(p!=='1234'||!['admin','teacher','viewer'].includes(u.toLowerCase()))return;state.user={username:u,role:u==='admin'?'Admin':u==='teacher'?'Teacher':'Viewer'};localStorage.setItem('sa_user',JSON.stringify(state.user));openApp();load()}
function openApp(){$('login').classList.remove('show');$('app').classList.remove('hidden');$('roleBadge').textContent=`${state.user.role} • ${state.user.username}`}
function logout(){state.user=null;localStorage.removeItem('sa_user');location.reload()}
async function load(){try{let j=await api('bootstrap');Object.assign(state,j)}catch(e){loadLocal()}renderAll()}
function loadLocal(){state.students=JSON.parse(localStorage.getItem('sa_students')||'[]');state.timetable=JSON.parse(localStorage.getItem('sa_timetable')||'[]');if(!state.timetable.length)state.timetable=[[1,'Data Structures','09:00','10:00'],[2,'Operating Systems','10:00','11:00'],[3,'DBMS','11:15','12:15'],[4,'Computer Networks','12:15','13:15'],[5,'Python','14:00','15:00'],[6,'AI & ML','15:00','16:00'],[7,'Web Technology','16:00','17:00'],[8,'Project','17:00','18:00']].map(x=>({lecture_no:x[0],subject:x[1],start_time:x[2],end_time:x[3]}));state.attendance=JSON.parse(localStorage.getItem('sa_att')||'[]');state.movement=JSON.parse(localStorage.getItem('sa_mov')||'[]');state.holidays=JSON.parse(localStorage.getItem('sa_hol')||'[]');state.notifications=JSON.parse(localStorage.getItem('sa_notif')||'[]')}
function persist(){for(const [k,v] of [['students',state.students],['timetable',state.timetable],['att',state.attendance],['mov',state.movement],['hol',state.holidays],['notif',state.notifications]])localStorage.setItem('sa_'+k,JSON.stringify(v))}
function showPage(id){document.querySelectorAll('.page').forEach(x=>x.classList.add('hidden'));$(id).classList.remove('hidden');renderAll()}
function isSunday(d=new Date()){return d.getDay()===0}function holiday(){let h=state.holidays.find(x=>String(x.holiday_date||x.date).slice(0,10)===dateStr());return isSunday(new Date())?(true,'Sunday','Automatic'):h?[true,h.name,h.holiday_type]:[false,'','']}
function minutes(t){let [h,m]=String(t).split(':').map(Number);return h*60+m}function currentLecture(){let n=new Date();let cur=n.getHours()*60+n.getMinutes();return state.timetable.find(l=>cur>=minutes(l.start_time)&&cur<minutes(l.end_time))}
function timing(l){if(!l)return 'NO ACTIVE LECTURE';let now=new Date(),cur=now.getHours()*60+now.getMinutes()+now.getSeconds()/60,s=minutes(l.start_time),e=minutes(l.end_time);if(cur>=s&&cur<s+grace)return 'PRESENT WINDOW';if(cur>=s+grace&&cur<e-finalWindow)return 'LATE WINDOW';if(cur>=e-finalWindow&&cur<e)return 'FINAL OUT WINDOW';return cur>=e?'ENDED':'LECTURE RUNNING'}
function renderAll(){clock();renderDashboard();renderStudents();renderTimetable();renderReports();renderCalendar();renderNotifications();fillLectureSelect();setInterval(clock,1000);}
let clockStarted=false;function clock(){ $('clock').textContent=new Date().toLocaleString();let l=currentLecture();$('liveLecture').innerHTML=l?`<b>LECTURE ${l.lecture_no}</b> — ${l.subject} — ${l.start_time} to ${l.end_time}<br><span>${timing(l)}</span>`:'NO ACTIVE LECTURE';let h=holiday();$('holidayBanner').innerHTML=h[0]?`<strong>Attendance disabled:</strong> ${h[1]} (${h[2]})`:'';finalizeFinished();if(!clockStarted){clockStarted=true;setInterval(clock,1000)}}
function esc(s){return String(s??'').replace(/[&<>"']/g,c=>({'&':'&amp;','<':'&lt;','>':'&gt;','"':'&quot;',"'":'&#39;'}[c]))}function table(el,heads,rows){$(el).innerHTML='<thead><tr>'+heads.map(esc).map(x=>`<th>${x}</th>`).join('')+'</tr></thead><tbody>'+rows.map(r=>'<tr>'+r.map(x=>`<td>${esc(x)}</td>`).join('')+'</tr>').join('')+'</tbody>'}
function renderDashboard(){ $('statStudents').textContent=state.students.length;let td=state.attendance.filter(a=>String(a.attendance_date||a.Date).slice(0,10)===dateStr());$('statPresent').textContent=td.filter(a=>a.status==='Present').length;$('statLate').textContent=td.filter(a=>a.status==='Late').length;$('statOut').textContent=state.movement.filter(m=>String(m.attendance_date||m.date).slice(0,10)===dateStr()&&m.movement_type==='OUT').length;table('dashTable',['Date','Lecture','Student','Status','IN','OUT'],td.map(a=>[a.attendance_date,a.lecture_no,a.name||a.student_id,a.status,a.in_time,a.out_time]))}
function renderStudents(){table('studentTable',['ID','Name','Roll','Course','Sem','Section','Parent Mobile','Parent Email'],state.students.map(s=>[s.student_id,s.name,s.roll_no,s.course,s.semester,s.section,s.parent_mobile,s.parent_email]));$('notifStudent').innerHTML=state.students.map(s=>`<option value="${esc(s.student_id)}">${esc(s.student_id)} — ${esc(s.name)}</option>`).join('')}
function fillLectureSelect(){$('lectureSelect').innerHTML=state.timetable.map(l=>`<option value="${l.lecture_no}">Lecture ${l.lecture_no} — ${esc(l.subject)} (${l.start_time}-${l.end_time})</option>`).join('')}
function renderTimetable(){table('timeTable',['No','Subject','Start','End'],state.timetable.map(l=>[l.lecture_no,l.subject,l.start_time,l.end_time]))}
function renderReports(){let q=($('searchReport')?.value||'').toLowerCase(),f=$('statusFilter')?.value||'All';let rows=state.attendance.filter(a=>(f==='All'||a.status===f)&&(JSON.stringify(a).toLowerCase().includes(q)));table('reportTable',['Date','Lecture','Student ID','Name','Status','IN','OUT'],rows.map(a=>[a.attendance_date,a.lecture_no,a.student_id,a.name||'',a.status,a.in_time,a.out_time]))}
function renderCalendar(){table('holidayTable',['Date','Name','Type'],state.holidays.map(h=>[h.holiday_date,h.name,h.holiday_type]))}
function renderNotifications(){table('notifTable',['Time','Student','Channel','Recipient','Subject','Status','Message'],state.notifications.map(n=>[n.sent_at||'',n.student_name,n.channel,n.recipient,n.subject,n.status,n.message]))}
async function saveStudent(){let s={student_id:$('sid').value.trim(),name:$('sname').value.trim(),roll_no:$('roll').value,course:$('course').value,semester:$('semester').value,section:$('section').value,parent_mobile:$('pmobile').value,parent_email:$('pemail').value,face_descriptor:window.pendingDescriptor||null};if(!s.student_id||!s.name)return alert('Student ID and Name required');try{await api('students',{method:'POST',body:JSON.stringify(s)})}catch(e){}let i=state.students.findIndex(x=>x.student_id===s.student_id);if(i>=0)state.students[i]=s;else state.students.push(s);persist();alert('Student saved');renderStudents()}
async function deleteStudent(){let id=$('sid').value.trim();if(!id)return alert('Enter Student ID');if(state.user.role!=='Admin')return alert('Admin only');if(!confirm('Delete this student?'))return;try{await api('students',{method:'DELETE',query:`&id=${encodeURIComponent(id)}`})}catch(e){}state.students=state.students.filter(s=>s.student_id!==id);persist();renderStudents()}
async function loadModels(){if(state.descriptorsLoaded)return;$('regStatus').textContent='Loading face models...';await faceapi.nets.tinyFaceDetector.loadFromUri('https://justadudewhohacks.github.io/face-api.js/models');await faceapi.nets.faceLandmark68Net.loadFromUri('https://justadudewhohacks.github.io/face-api.js/models');await faceapi.nets.faceRecognitionNet.loadFromUri('https://justadudewhohacks.github.io/face-api.js/models');state.descriptorsLoaded=true}
async function camera(streamId){let s=await navigator.mediaDevices.getUserMedia({video:{facingMode:'user'},audio:false});$(streamId).srcObject=s;return s}
async function captureFaceForStudent(){try{await loadModels();if(!state.regStream)state.regStream=await camera('regVideo');let d=await faceapi.detectSingleFace($('regVideo'),new faceapi.TinyFaceDetectorOptions()).withFaceLandmarks().withFaceDescriptor();if(!d){$('regStatus').textContent='No clear face detected';return}window.pendingDescriptor=Array.from(d.descriptor);$('regStatus').textContent='Face captured successfully'}catch(e){$('regStatus').textContent='Camera/face model error: '+e.message}}
async function startCamera(){if(holiday()[0])return alert(`Today is a holiday: ${holiday()[1]}. Attendance disabled.`);if(!state.students.some(s=>s.face_descriptor||s.faceDescriptor))return alert('No registered face descriptors. Register students first.');try{await loadModels();state.stream=await camera('video');$('cameraStatus').textContent='Camera running — scanning faces';scanLoop()}catch(e){alert(e.message)}}
function stopCamera(){if(state.stream){state.stream.getTracks().forEach(t=>t.stop());state.stream=null}$('cameraStatus').textContent='Camera stopped'}
let scanning=false,lastSeen={};async function scanLoop(){if(!state.stream||scanning)return;scanning=true;const video=$('video'),canvas=$('overlay');canvas.width=video.videoWidth||900;canvas.height=video.videoHeight||500;const results=await faceapi.detectAllFaces(video,new faceapi.TinyFaceDetectorOptions()).withFaceLandmarks().withFaceDescriptors();let current=new Set();for(const d of results){let best=null,bestDist=1;for(const s of state.students){let desc=s.face_descriptor||s.faceDescriptor;if(!desc)continue;let dist=faceapi.euclideanDistance(d.descriptor,new Float32Array(desc));if(dist<bestDist){bestDist=dist;best=s}}if(best&&bestDist<0.52){current.add(best.student_id);await processRecognition(best,lastSeen[best.student_id]===true);}}for(const id in lastSeen)if(!current.has(id))lastSeen[id]=false;for(const id of current)lastSeen[id]=true;scanning=false;if(state.stream)requestAnimationFrame(scanLoop)}
async function processRecognition(s,wasVisible){let l=currentLecture();if(!l||wasVisible)return;let now=new Date(),cur=now.getHours()*60+now.getMinutes()+now.getSeconds()/60;if(cur>=minutes(l.start_time)&&cur<minutes(l.start_time)+grace)await markIn(s,l,'Present');else if(cur>=minutes(l.start_time)+grace&&cur<minutes(l.end_time))await markIn(s,l,'Late');let st=currentMovement(s.student_id,l.lecture_no);if(st==='OUT')await movementIn(s,l);if(state.tempRequested&&st==='IN'){await movementOut(s,l);state.tempRequested=false}if(cur>=minutes(l.end_time)-finalWindow&&cur<minutes(l.end_time))await finalOut(s,l)}
function currentMovement(id,ln){let rows=state.movement.filter(m=>m.student_id===id&&m.lecture_no===ln&&String(m.attendance_date||m.date).slice(0,10)===dateStr());return rows.length?rows[0].movement_type==='OUT'?'OUT':'IN':'IN'}
async function markIn(s,l,status){if(state.attendance.some(a=>a.student_id===s.student_id&&String(a.attendance_date).slice(0,10)===dateStr()&&a.lecture_no===l.lecture_no&&a.in_time))return;let a={student_id:s.student_id,name:s.name,course:s.course,attendance_date:dateStr(),lecture_no:l.lecture_no,lecture_start:l.start_time,lecture_end:l.end_time,in_time:timeStr(),out_time:'',status};state.attendance.push(a);persist();try{await api('attendance',{method:'POST',body:JSON.stringify({action:'in',...a})})}catch(e){}renderDashboard();renderReports()}
async function finalOut(s,l){let a=state.attendance.find(x=>x.student_id===s.student_id&&String(x.attendance_date).slice(0,10)===dateStr()&&x.lecture_no===l.lecture_no&&x.in_time&&!x.out_time);if(!a)return;a.out_time=l.end_time+':00';persist();try{await api('attendance',{method:'POST',body:JSON.stringify({action:'final_out',student_id:s.student_id,lecture_no:l.lecture_no,lecture_end:a.out_time})})}catch(e){}renderDashboard()}
function tempOutRequest(){if(!currentLecture())return alert('No active lecture.');state.tempRequested=true;alert('Temporary OUT requested. Show the student face to camera. Reason: Toilet / Water.')}
async function movementOut(s,l){let m={student_id:s.student_id,attendance_date:dateStr(),lecture_no:l.lecture_no,movement_type:'OUT',event_time:timeStr(),reason:'Toilet / Water'};state.movement.unshift(m);persist();try{await api('movement',{method:'POST',body:JSON.stringify(m)})}catch(e){}renderDashboard()}
async function movementIn(s,l){let m={student_id:s.student_id,attendance_date:dateStr(),lecture_no:l.lecture_no,movement_type:'IN',event_time:timeStr(),reason:'Return'};state.movement.unshift(m);persist();try{await api('movement',{method:'POST',body:JSON.stringify(m)})}catch(e){}renderDashboard()}
async function finalOutVisible(){let l=currentLecture();if(!l||timing(l)!=='FINAL OUT WINDOW')return alert('Final OUT is available only during the last 5 minutes.');alert('Final OUT is automatic when a recognized student is visible in the final window.')}
function finalizeFinished(){let cur=new Date(),mins=cur.getHours()*60+cur.getMinutes()+cur.getSeconds()/60;let changed=false;for(const a of state.attendance){let l=state.timetable.find(x=>x.lecture_no===a.lecture_no);if(!l||String(a.attendance_date).slice(0,10)!==dateStr()||!a.in_time||a.out_time)continue;if(mins>=minutes(l.end_time)){a.out_time=l.end_time+':00';changed=true}}if(changed){persist();renderDashboard();}}

async function saveTimetable(){let t={lecture_no:Number($('tn').value),subject:$('tsub').value,start_time:$('tstart').value,end_time:$('tend').value};if(!t.lecture_no||!t.subject)return alert('Lecture no and subject required');try{await api('timetable',{method:'POST',body:JSON.stringify(t)})}catch(e){}state.timetable=state.timetable.filter(x=>x.lecture_no!==t.lecture_no);state.timetable.push(t);state.timetable.sort((a,b)=>a.lecture_no-b.lecture_no);persist();fillLectureSelect();renderTimetable()}
function exportCSV(){let rows=[['Date','Lecture','Student ID','Name','Status','IN','OUT'],...state.attendance.map(a=>[a.attendance_date,a.lecture_no,a.student_id,a.name,a.status,a.in_time,a.out_time])];let csv=rows.map(r=>r.map(x=>'"'+String(x??'').replaceAll('"','""')+'"').join(',')).join('\n');let a=document.createElement('a');a.href=URL.createObjectURL(new Blob([csv],{type:'text/csv'}));a.download='attendance_report.csv';a.click()}
async function addHoliday(){let h={holiday_date:$('hdate').value,name:$('hname').value,holiday_type:$('htype').value||'College Custom'};if(!h.holiday_date||!h.name)return alert('Date and name required');try{await api('holiday',{method:'POST',body:JSON.stringify(h)})}catch(e){}state.holidays.push(h);persist();renderCalendar()}
async function queueNotification(){let s=state.students.find(x=>x.student_id===$('notifStudent').value);if(!s)return;let channel=$('notifChannel').value,recipient=channel==='Email'?s.parent_email:s.parent_mobile,n={student_id:s.student_id,student_name:s.name,channel,recipient,subject:$('notifSubject').value,message:$('notifMessage').value,status:'Queued',sent_at:new Date().toISOString()};state.notifications.unshift(n);persist();try{await api('notifications',{method:'POST',body:JSON.stringify(n)})}catch(e){}renderNotifications();alert('Notification queued. Real WhatsApp/SMS/Email delivery needs provider credentials on the server; never put secrets in browser JS.')}
function attendancePercent(s){let sessions=state.timetable.length*new Set(state.attendance.map(a=>a.attendance_date)).size||1;let present=state.attendance.filter(a=>a.student_id===s.student_id&&(a.status==='Present'||a.status==='Late')).length;return (present/Math.max(1,sessions)*100)}
function showPerformance(){let rows=state.students.map(s=>`${s.student_id} — ${s.name}: ${attendancePercent(s).toFixed(1)}%`);$('advancedOutput').innerHTML='<h3>Student Performance</h3>'+rows.map(esc).join('<br>')}
function showLowAlerts(){let threshold=75,rows=state.students.filter(s=>attendancePercent(s)<threshold);$('advancedOutput').innerHTML='<h3>Low Attendance Alerts (&lt;75%)</h3>'+(rows.length?rows.map(s=>`${esc(s.name)} — ${attendancePercent(s).toFixed(1)}%`).join('<br>'):'No low-attendance students')}
function showProfile(){let s=state.students[0];$('advancedOutput').innerHTML=s?`<h3>Student Profile</h3><b>${esc(s.name)}</b><br>ID: ${esc(s.student_id)}<br>Roll: ${esc(s.roll_no)}<br>Course: ${esc(s.course)}<br>Semester: ${esc(s.semester)}<br>Section: ${esc(s.section)}`:'No students'}
async function showAudit(){try{let j=await api('bootstrap');$('advancedOutput').innerHTML='<h3>Audit / Role Protection</h3><p>Web API records logins and administrative events server-side when DATABASE_URL is configured.</p><pre>'+esc(JSON.stringify(j.users,null,2))+'</pre>'}catch(e){$('advancedOutput').innerHTML='<h3>Audit</h3><p>Database audit is unavailable in local fallback mode.</p>'}}
function systemHealth(){$('advancedOutput').innerHTML=`<h3>System Health</h3><p>Browser: ${esc(navigator.userAgent)}</p><p>Camera API: ${navigator.mediaDevices?'Available':'Unavailable'}</p><p>Face models: ${state.descriptorsLoaded?'Loaded':'Not loaded'}</p><p>Database: Vercel API attempts Neon when configured; otherwise localStorage fallback.</p>`}
function tamperInfo(){$('advancedOutput').innerHTML='<h3>Tamper Protection</h3><p>Role checks are enforced in the UI and the API. Audit logs are stored server-side when a database is configured. Do not trust browser-only role checks for production security.</p>'}
function qrInfo(){$('advancedOutput').innerHTML='<h3>Student QR</h3><p>The Python version generates one QR per Student_ID. This web conversion keeps Student_ID as the QR payload; connect a QR scanner library/device to populate the student ID for backup/check-in workflows.</p>'}
function backupInfo(){$('advancedOutput').innerHTML='<h3>Backup / Restore</h3><p>For Neon/Postgres, use database backups/export from the provider. Browser localStorage can be exported only by adding a JSON backup endpoint; direct database replacement is intentionally server-side.</p>'}
async function faceQuality(){try{await loadModels();if(!state.regStream)state.regStream=await camera('regVideo');let d=await faceapi.detectSingleFace($('regVideo'),new faceapi.TinyFaceDetectorOptions());$('advancedOutput').innerHTML=d?'<h3>Face Quality</h3><p>Face detected. Keep the face centered, visible and well lit, then capture.</p>':'<h3>Face Quality</h3><p>No face detected. Move into frame and improve lighting.</p>'}catch(e){$('advancedOutput').textContent=e.message}}
function duplicateInfo(){$('advancedOutput').innerHTML='<h3>Duplicate Protection</h3><p>One attendance row per Student + Date + Lecture is accepted. Browser recognition also waits for a face to disappear before treating it as a new appearance, matching the desktop program’s duplicate-IN protection.</p>'}
window.addEventListener('load',()=>{let u=JSON.parse(localStorage.getItem('sa_user')||'null');if(u){state.user=u;openApp();load()}setTimeout(()=>{$('splash').style.opacity='0';setTimeout(()=>$('splash').remove(),800)},2600)})
